apiVersion: v1
kind: Service
metadata:
  name: cloud6-coredns-metrics
  labels:
    tier: server
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    tier: server
