apiVersion: v1
kind: Service
metadata:
  name: cloud6-coredns
  labels:
    tier: server
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    tier: server
